# 隨機森林 random forest

In [116]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as sns
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor
from sklearn import metrics
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score
%matplotlib inline

# 導入數據 
dataset = pd.read_csv(r'C:/Users/Cindy/Desktop/0728test.csv')
dataset

,Number,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,...,Input_C_134,Input_C_135,Input_C_136,Input_C_137,Output_A1,Output_A2,Output_A3,Output_A4,Output_A5,Output_A6
0,Test1,0.00,0.00,0.00,0.00,0.00,0.002,0.004,0.002,0.004,...,-0.004,4.00,1.0,1.0,3.202,4.280,2.804,4.805,3.178,2.888
1,Test2,0.00,0.00,0.00,0.00,0.00,0.016,0.004,0.002,0.004,...,0.003,4.00,1.0,1.0,4.303,4.113,2.949,3.073,3.539,4.187
2,Test3,0.00,0.00,0.00,0.00,0.00,0.006,0.006,0.002,0.002,...,-0.003,3.70,1.0,1.0,4.078,3.672,4.303,4.508,3.734,3.013
3,Test4,0.00,0.00,0.02,0.04,0.07,0.004,0.005,0.002,0.005,...,0.004,4.00,0.0,0.0,3.816,3.928,2.827,3.098,3.616,3.018
4,Test5,0.00,0.00,0.00,0.00,0.00,0.012,0.008,0.002,0.003,...,0.004,4.00,1.0,1.0,4.015,3.672,4.514,4.165,3.856,3.494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,Test91,0.00,0.00,0.00,0.00,0.00,0.014,0.014,0.002,0.004,...,0.005,0.04,1.0,3.0,4.201,3.300,4.069,3.265,3.602,3.921
91,Test92,0.00,0.00,0.02,0.04,0.09,0.010,0.004,0.002,0.004,...,0.004,0.04,1.0,2.0,3.050,3.502,3.252,3.169,3.689,3.909
92,Test93,0.00,0.00,0.00,0.00,0.00,0.014,0.014,0.002,0.005,...,0.004,0.04,2.0,2.0,3.561,3.739,3.243,3.779,3.113,3.592
93,Test94,0.08,0.06,0.03,0.00,0.00,0.006,0.010,0.002,0.004,...,-0.005,0.04,2.0,2.0,2.863,3.962,3.145,3.212,3.156,3.647
94,Test95,0.00,0.00,0.00,0.00,0.00,0.008,0.014,0.002,0.004,...,0.006,0.04,2.0,2.0,3.021,3.604,3.480,3.106,3.908,3.114

In [117]:
dataset.describe()

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_C_134,Input_C_135,Input_C_136,Input_C_137,Output_A1,Output_A2,Output_A3,Output_A4,Output_A5,Output_A6
count,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,9.500000e+01,95.000000,9.500000e+01,...,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000
mean,0.014842,0.011474,0.009263,0.011053,0.018526,0.007042,0.010958,2.000000e-03,0.003579,2.000000e-03,...,0.000705,2.701263,1.226316,1.278947,3.695895,3.614347,3.649505,3.509537,3.675200,3.482221
std,0.035366,0.028433,0.015522,0.016010,0.030246,0.004307,0.006380,1.307945e-18,0.001107,1.307945e-18,...,0.004955,1.736028,0.529795,0.572953,0.427978,0.445974,0.479365,0.488951,0.439592,0.464481
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.002000,0.002000,2.000000e-03,0.002000,2.000000e-03,...,-0.008000,0.040000,0.000000,0.000000,2.863000,2.810000,2.804000,2.810000,2.844000,2.827000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.003500,0.006000,2.000000e-03,0.003000,2.000000e-03,...,-0.004500,0.040000,1.000000,1.000000,3.395500,3.283000,3.290000,3.111000,3.378500,3.132500
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.006000,0.009000,2.000000e-03,0.004000,2.000000e-03,...,0.004000,3.700000,1.000000,1.000000,3.671000,3.603000,3.638000,3.396000,3.668000,3.373000
75%,0.000000,0.000000,0.020000,0.020000,0.040000,0.010000,0.016000,2.000000e-03,0.004500,2.000000e-03,...,0.005000,3.950000,2.000000,2.000000,3.988000,3.876000,3.943500,3.773500,3.943500,3.717500
max,0.170000,0.150000,0.080000,0.070000,0.120000,0.018000,0.026000,2.000000e-03,0.005000,2.000000e-03,...,0.008000,4.200000,2.000000,3.000000,4.987000,4.763000,4.847000,4.805000,4.877000,5.296000

In [118]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Columns: 268 entries, Number to Output_A6
dtypes: float64(218), int64(5), object(45)
memory usage: 199.0+ KB

In [119]:
X = dataset.iloc[:,1:24]
y = dataset['Output_A1']

In [120]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=101)
#60%為Training set，40%為Test set
# test_size代表測試組比例。
# random_state代表設定隨機種子，讓測試結果可被重複

In [121]:
#建立一個模型model
clf = RandomForestRegressor(n_estimators=10)
#放進模型內訓練
clf.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [122]:
y_pred = clf.predict(X_test)
y_pred

array([3.7197, 3.7156, 4.0973, 3.6825, 3.4051, 3.4969, 3.3574, 3.3583,
       3.7847, 3.668 , 3.5235, 3.5497, 3.8098, 3.4645, 3.9088, 3.3051,
       3.5699, 3.5966, 3.6358, 3.5768, 3.3875, 3.757 , 3.6713, 3.4527,
       3.4673, 3.8366, 3.8142, 3.6705, 4.0565, 3.2986, 3.6196, 3.667 ,
       3.4466, 3.342 , 3.1077, 3.6998, 3.4844, 3.4824])

In [123]:
#顯示實際值和預測值
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df

    Actual  Predicted
53   3.910     3.7197
6    3.414     3.7156
58   4.086     4.0973
16   3.670     3.6825
90   4.201     3.4051
43   4.042     3.4969
65   3.532     3.3574
48   4.016     3.3583
41   3.987     3.7847
85   4.339     3.6680
57   3.878     3.5235
21   3.559     3.5497
47   3.786     3.8098
3    3.816     3.4645
73   3.313     3.9088
1    4.303     3.3051
78   3.701     3.5699
45   3.656     3.5966
37   3.922     3.6358
54   3.109     3.5768
2    4.078     3.3875
13   3.989     3.7570
82   3.211     3.6713
25   4.551     3.4527
80   3.738     3.4673
32   3.518     3.8366
50   3.562     3.8142
14   3.914     3.6705
23   4.406     4.0565
55   3.529     3.2986
31   3.939     3.6196
26   3.737     3.6670
22   3.866     3.4466
68   3.165     3.3420
27   3.963     3.1077
20   4.196     3.6998
67   3.788     3.4844
30   4.229     3.4824

In [124]:
accuracy_score(y_test.astype(int), y_pred.astype(int))
#轉成int才會成功。但是轉乘int的準確值就會降低

0.7631578947368421

In [125]:
accuracy_score(y_test, y_pred)
#如果不轉成int就會出現錯誤

ValueError: continuous is not supported