In [15]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as sns
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
# 導入LogisticRegression方法
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
%matplotlib inline

# 導入數據 
dataset = pd.read_csv(r'C:/Users/Cindy/Desktop/0728test.csv')
dataset

,Number,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,...,Input_C_134,Input_C_135,Input_C_136,Input_C_137,Output_A1,Output_A2,Output_A3,Output_A4,Output_A5,Output_A6
0,Test1,0.00,0.00,0.00,0.00,0.00,0.002,0.004,0.002,0.004,...,-0.004,4.00,1.0,1.0,3.202,4.280,2.804,4.805,3.178,2.888
1,Test2,0.00,0.00,0.00,0.00,0.00,0.016,0.004,0.002,0.004,...,0.003,4.00,1.0,1.0,4.303,4.113,2.949,3.073,3.539,4.187
2,Test3,0.00,0.00,0.00,0.00,0.00,0.006,0.006,0.002,0.002,...,-0.003,3.70,1.0,1.0,4.078,3.672,4.303,4.508,3.734,3.013
3,Test4,0.00,0.00,0.02,0.04,0.07,0.004,0.005,0.002,0.005,...,0.004,4.00,0.0,0.0,3.816,3.928,2.827,3.098,3.616,3.018
4,Test5,0.00,0.00,0.00,0.00,0.00,0.012,0.008,0.002,0.003,...,0.004,4.00,1.0,1.0,4.015,3.672,4.514,4.165,3.856,3.494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,Test91,0.00,0.00,0.00,0.00,0.00,0.014,0.014,0.002,0.004,...,0.005,0.04,1.0,3.0,4.201,3.300,4.069,3.265,3.602,3.921
91,Test92,0.00,0.00,0.02,0.04,0.09,0.010,0.004,0.002,0.004,...,0.004,0.04,1.0,2.0,3.050,3.502,3.252,3.169,3.689,3.909
92,Test93,0.00,0.00,0.00,0.00,0.00,0.014,0.014,0.002,0.005,...,0.004,0.04,2.0,2.0,3.561,3.739,3.243,3.779,3.113,3.592
93,Test94,0.08,0.06,0.03,0.00,0.00,0.006,0.010,0.002,0.004,...,-0.005,0.04,2.0,2.0,2.863,3.962,3.145,3.212,3.156,3.647
94,Test95,0.00,0.00,0.00,0.00,0.00,0.008,0.014,0.002,0.004,...,0.006,0.04,2.0,2.0,3.021,3.604,3.480,3.106,3.908,3.114

In [16]:
X = dataset.iloc[:,1:24]
y = dataset['Output_A1']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=101)

In [18]:
from sklearn.neighbors import KNeighborsClassifier
#定義分類器
knn = KNeighborsClassifier()
#進行分類
knn.fit(X_train, y_train.astype('int'))
KNeighborsClassifier()
y_predict=knn.predict(X_test)

y_test = np.array(list(y_test))
y_pred = np.array(y_predict)
#顯示實際值和預測值
df = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_predict.flatten()})
df

    Actual  Predicted
0    3.910          3
1    3.414          3
2    4.086          4
3    3.670          4
4    4.201          3
5    4.042          3
6    3.532          3
7    4.016          3
8    3.987          3
9    4.339          4
10   3.878          3
11   3.559          3
12   3.786          3
13   3.816          3
14   3.313          4
15   4.303          3
16   3.701          3
17   3.656          3
18   3.922          3
19   3.109          3
20   4.078          3
21   3.989          3
22   3.211          3
23   4.551          3
24   3.738          3
25   3.518          3
26   3.562          3
27   3.914          3
28   4.406          3
29   3.529          3
30   3.939          3
31   3.737          3
32   3.866          3
33   3.165          3
34   3.963          3
35   4.196          3
36   3.788          3
37   4.229          3

In [19]:
# 計算準確率, 由于每次數據集劃分不同, 可能不一样
# fabs 絕對值
print( np.sum(np.fabs(y_predict - y_test)) / float(len(y_test)))

0.7803421052631578

In [20]:
# 平均絕對誤差(MAE)、均方誤差(MSE)、均方根誤差(RMSE)
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_predict))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_predict))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_predict)))

Mean Absolute Error: 0.7803421052631578
Mean Squared Error: 0.733454657894737
Root Mean Squared Error: 0.8564196739302157