In [206]:
import pandas as pd 
import matplotlib.pyplot as plt 
# 導入數據 
data = pd.read_csv(r'C:/Users/Cindy/Desktop/0714train.csv')
Input1=data.iloc[:,1:25]
Input2=data.iloc[:,1:25]
Input3=data.iloc[:,1:25]
Input1

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
0,0.00,0.00,0.00,0.00,0.00,0.016,0.010,0.002,0.004,0.002,...,-0.02,-0.02,-0.03,-0.01,-0.03,0.1,0.500,0.0,0.0,0.0
1,0.00,0.00,0.00,0.00,0.00,0.002,0.013,0.002,0.002,0.002,...,-0.02,-0.02,-0.03,-0.02,-0.02,0.2,0.600,0.0,0.0,0.0
2,0.00,0.00,0.00,0.03,0.05,0.002,0.014,0.002,0.002,0.002,...,0.04,-0.04,-0.04,-0.05,-0.04,0.1,0.576,0.0,0.0,0.0
3,0.00,0.00,0.00,0.00,0.02,0.003,0.010,0.002,0.004,0.002,...,0.05,-0.02,-0.03,-0.01,-0.02,1.0,0.600,0.0,0.0,0.0
4,0.00,0.00,0.00,0.02,0.04,0.006,0.020,0.002,0.004,0.002,...,0.02,-0.05,-0.03,-0.03,-0.05,0.0,0.523,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,0.12,0.09,0.05,0.02,0.00,0.004,0.020,0.002,0.003,0.002,...,-0.02,-0.02,-0.03,-0.02,-0.02,0.2,0.500,0.0,0.0,0.0
344,0.00,0.00,0.00,0.00,0.00,0.006,0.020,0.002,0.004,0.002,...,0.05,-0.02,-0.02,-0.02,-0.02,0.5,0.547,0.0,0.0,0.0
345,0.00,0.00,0.00,0.02,0.04,0.002,0.004,0.002,0.004,0.002,...,-0.02,-0.01,-0.03,-0.02,-0.02,0.1,0.574,0.0,0.0,0.0
346,0.00,0.00,0.00,0.00,0.00,0.002,0.005,0.002,0.005,0.002,...,-0.02,-0.02,-0.02,-0.03,-0.02,0.1,0.500,0.0,0.0,0.0
347,0.10,0.08,0.04,0.02,0.00,0.002,0.005,0.002,0.005,0.002,...,-0.02,-0.02,-0.02,-0.04,-0.02,1.1,0.547,0.0,0.0,0.0

In [192]:
pd.DataFrame(Input1).describe()

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
count,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,3.480000e+02,...,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,348.000000,348.000000,348.000000
mean,0.022874,0.018103,0.012557,0.017270,0.021178,0.005991,0.009667,0.002006,0.003382,2.000000e-03,...,0.007607,-0.027283,-0.027977,-0.027659,-0.027225,0.521387,0.549717,-0.000259,-0.000172,-0.000086
std,0.046779,0.038694,0.020500,0.047627,0.032962,0.004383,0.005227,0.000107,0.001093,1.302916e-18,...,0.030379,0.012470,0.011744,0.012944,0.012457,0.796117,0.049800,0.003749,0.002512,0.004771
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.001000,0.002000,0.002000,0.002000,2.000000e-03,...,-0.050000,-0.050000,-0.050000,-0.050000,-0.050000,0.000000,0.400000,-0.020000,-0.010000,-0.030000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.002000,0.005000,0.002000,0.002000,2.000000e-03,...,-0.020000,-0.040000,-0.040000,-0.040000,-0.040000,0.100000,0.521000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.004000,0.010000,0.002000,0.003000,2.000000e-03,...,0.020000,-0.020000,-0.030000,-0.030000,-0.030000,0.200000,0.562000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.030000,0.020000,0.040000,0.008000,0.014000,0.002000,0.004000,2.000000e-03,...,0.030000,-0.020000,-0.020000,-0.020000,-0.020000,1.000000,0.600000,0.000000,0.000000,0.000000
max,0.280000,0.260000,0.130000,0.820000,0.160000,0.020000,0.028000,0.004000,0.005000,2.000000e-03,...,0.050000,-0.010000,-0.010000,-0.010000,-0.010000,5.300000,0.600000,0.020000,0.010000,0.020000

In [193]:
a=pd.DataFrame(Input1).describe()
a.loc['IQR'] ='' 
a.loc['fence_max'] ='' 
a.loc['fence_min'] ='' 
for i in range(24):
    a.iloc[8,i]=a.iloc[6,i]-a.iloc[4,i]
    a.iloc[9,i]=a.iloc[6,i] + 1.5 * a.iloc[8,i]
    a.iloc[10,i]=a.iloc[4,i] - 1.5 * a.iloc[8,i]
a

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
count,348,348,348,348,348,348,348,348,348,348,...,346,346,346,346,346,346,346,348,348,348
mean,0.0228736,0.0181034,0.0125575,0.0172701,0.0211782,0.00599138,0.00966667,0.00200575,0.00338218,0.002,...,0.00760694,-0.0272832,-0.0279769,-0.027659,-0.0272254,0.521387,0.549717,-0.000258621,-0.000172414,-8.62069e-05
std,0.0467788,0.0386944,0.0204998,0.0476269,0.0329622,0.00438328,0.00522666,0.000107211,0.00109251,1.30292e-18,...,0.0303788,0.0124698,0.0117441,0.012944,0.012457,0.796117,0.0498,0.00374886,0.00251202,0.00477065
min,0,0,0,0,0,0.001,0.002,0.002,0.002,0.002,...,-0.05,-0.05,-0.05,-0.05,-0.05,0,0.4,-0.02,-0.01,-0.03
25%,0,0,0,0,0,0.002,0.005,0.002,0.002,0.002,...,-0.02,-0.04,-0.04,-0.04,-0.04,0.1,0.521,0,0,0
50%,0,0,0,0,0,0.004,0.01,0.002,0.003,0.002,...,0.02,-0.02,-0.03,-0.03,-0.03,0.2,0.562,0,0,0
75%,0,0,0.03,0.02,0.04,0.008,0.014,0.002,0.004,0.002,...,0.03,-0.02,-0.02,-0.02,-0.02,1,0.6,0,0,0
max,0.28,0.26,0.13,0.82,0.16,0.02,0.028,0.004,0.005,0.002,...,0.05,-0.01,-0.01,-0.01,-0.01,5.3,0.6,0.02,0.01,0.02
IQR,0,0,0.03,0.02,0.04,0.006,0.009,0,0.002,0,...,0.05,0.02,0.02,0.02,0.02,0.9,0.079,0,0,0
fence_max,0,0,0.075,0.05,0.1,0.017,0.0275,0.002,0.007,0.002,...,0.105,0.01,0.01,0.01,0.01,2.35,0.7185,0,0,0
fence_min,0,0,-0.045,-0.03,-0.06,-0.007,-0.0085,0.002,-0.001,0.002,...,-0.095,-0.07,-0.07,-0.07,-0.07,-1.25,0.4025,0,0,0

In [194]:
d=Input1
for i in range(0,24):
    fmin=a.iloc[10,i]
    fmax=a.iloc[9,i]
    tf=((d.iloc[:,i] < fmin) | (d.iloc[:,i] > (fmax)))
    d.iloc[:,i]=tf
d

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
344,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
345,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
346,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
347,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [195]:
Input2

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
0,0.00,0.00,0.00,0.00,0.00,0.016,0.010,0.002,0.004,0.002,...,-0.02,-0.02,-0.03,-0.01,-0.03,0.1,0.500,0.0,0.0,0.0
1,0.00,0.00,0.00,0.00,0.00,0.002,0.013,0.002,0.002,0.002,...,-0.02,-0.02,-0.03,-0.02,-0.02,0.2,0.600,0.0,0.0,0.0
2,0.00,0.00,0.00,0.03,0.05,0.002,0.014,0.002,0.002,0.002,...,0.04,-0.04,-0.04,-0.05,-0.04,0.1,0.576,0.0,0.0,0.0
3,0.00,0.00,0.00,0.00,0.02,0.003,0.010,0.002,0.004,0.002,...,0.05,-0.02,-0.03,-0.01,-0.02,1.0,0.600,0.0,0.0,0.0
4,0.00,0.00,0.00,0.02,0.04,0.006,0.020,0.002,0.004,0.002,...,0.02,-0.05,-0.03,-0.03,-0.05,0.0,0.523,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,0.12,0.09,0.05,0.02,0.00,0.004,0.020,0.002,0.003,0.002,...,-0.02,-0.02,-0.03,-0.02,-0.02,0.2,0.500,0.0,0.0,0.0
344,0.00,0.00,0.00,0.00,0.00,0.006,0.020,0.002,0.004,0.002,...,0.05,-0.02,-0.02,-0.02,-0.02,0.5,0.547,0.0,0.0,0.0
345,0.00,0.00,0.00,0.02,0.04,0.002,0.004,0.002,0.004,0.002,...,-0.02,-0.01,-0.03,-0.02,-0.02,0.1,0.574,0.0,0.0,0.0
346,0.00,0.00,0.00,0.00,0.00,0.002,0.005,0.002,0.005,0.002,...,-0.02,-0.02,-0.02,-0.03,-0.02,0.1,0.500,0.0,0.0,0.0
347,0.10,0.08,0.04,0.02,0.00,0.002,0.005,0.002,0.005,0.002,...,-0.02,-0.02,-0.02,-0.04,-0.02,1.1,0.547,0.0,0.0,0.0

In [202]:
for j in range(0,24):
    for i in range (0,348):
        if d.iloc[i,j]==True:
            #得到離峰值位置及其數據
            print(j,i,Input3.iloc[i,j])

0 8 0.09
0 9 0.07
0 12 0.07
0 13 0.12
0 22 0.08
0 25 0.09
0 33 0.07
0 34 0.07
0 47 0.1
0 48 0.07
0 49 0.07
0 54 0.07
0 59 0.12
0 62 0.08
0 72 0.14
0 73 0.07
0 77 0.1
0 79 0.14
0 81 0.08
0 84 0.09
0 88 0.08
0 91 0.17
0 93 0.12
0 97 0.07
0 99 0.07
0 104 0.08
0 106 0.07
0 109 0.07
0 111 0.24
0 125 0.12
0 128 0.07
0 129 0.07
0 135 0.08
0 147 0.07
0 148 0.07
0 152 0.14
0 154 0.09
0 156 0.28
0 160 0.07
0 163 0.07
0 164 0.09
0 171 0.12
0 173 0.15
0 181 0.07
0 184 0.12
0 185 0.12
0 190 0.12
0 192 0.12
0 196 0.12
0 200 0.16
0 206 0.08
0 216 0.07
0 217 0.22
0 222 0.09
0 227 0.09
0 231 0.09
0 236 0.19
0 237 0.07
0 239 0.09
0 240 0.07
0 241 0.07
0 244 0.12
0 250 0.09
0 259 0.08
0 260 0.08
0 261 0.07
0 268 0.09
0 282 0.09
0 294 0.07
0 297 0.1
0 300 0.1
0 306 0.16
0 318 0.12
0 321 0.15
0 329 0.09
0 332 0.12
0 343 0.12
0 347 0.1
1 8 0.07
1 9 0.05
1 12 0.05
1 13 0.1
1 22 0.06
1 25 0.07
1 33 0.05
1 34 0.05
1 47 0.08
1 48 0.05
1 49 0.05
1 54 0.05
1 59 0.09
1 62 0.06
1 72 0.12
1 73 0.05
1 77 0.08
1 79 0.12
1 81 0.06
1 84 0.07
1 88 0.06
1 91 0.15
1 93 0.1
1 97 0.05
1 99 0.05
1 104 0.06
1 106 0.05
1 109 0.05
1 111 0.22
1 125 0.1
1 128 0.05
1 129 0.05
1 135 0.06
1 147 0.05
1 148 0.05
1 152 0.12
1 154 0.07
1 156 0.26
1 160 0.05
1 163 0.05
1 164 0.07
1 171 0.09
1 173 0.13
1 181 0.05
1 184 0.09
1 185 0.09
1 190 0.09
1 192 0.09
1 195 0.02
1 196 0.09
1 200 0.14
1 206 0.04
1 216 0.05
1 217 0.2
1 222 0.07
1 227 0.07
1 231 0.07
1 236 0.17
1 237 0.05
1 239 0.07
1 240 0.05
1 241 0.05
1 244 0.09
1 250 0.07
1 259 0.06
1 260 0.06
1 261 0.05
1 268 0.07
1 282 0.07
1 294 0.05
1 297 0.08
1 300 0.08
1 306 0.14
1 318 0.1
1 321 0.13
1 329 0.07
1 332 0.09
1 343 0.09
1 347 0.08
2 91 0.08
2 111 0.12
2 125 0.08
2 156 0.13
2 217 0.1
2 236 0.08
3 43 0.06
3 66 0.06
3 94 0.06
3 141 0.82
3 156 0.06
3 159 0.2
3 195 0.08
3 200 0.07
3 204 0.07
3 242 0.07
3 257 0.07
3 280 0.06
3 281 0.07
3 286 0.07
4 43 0.12
4 66 0.12
4 94 0.12
4 195 0.16
4 204 0.12
4 242 0.12
4 257 0.15
4 280 0.12
4 281 0.12
4 286 0.12
5 90 0.018000000000000002
5 95 0.018000000000000002
5 100 0.02
5 132 0.018000000000000002
5 149 0.018000000000000002
5 158 0.02
5 159 0.018000000000000002
6 8 0.027999999999999997
7 221 0.004
10 266 0.01
10 268 0.01
10 269 0.01
10 270 0.01
10 276 0.01
10 277 0.01
10 282 0.01
10 284 0.01
10 288 0.01
10 291 0.01
10 292 0.01
10 298 0.01
10 303 0.01
10 310 0.01
10 317 0.01
10 321 0.009000000000000001
10 323 0.01
10 325 0.01
10 329 0.01
10 330 0.01
10 331 0.01
10 332 0.01
10 335 0.01
10 336 0.01
10 338 0.01
10 344 0.01
10 345 0.01
10 346 0.01
10 347 0.01
19 25 3.0
19 48 3.5
19 49 3.2
19 69 3.2
19 78 3.1
19 93 3.5
19 113 5.0
19 117 3.1
19 135 3.0
19 141 2.6
19 158 5.3
19 161 3.6
19 211 3.2
19 239 2.8
20 19 0.4
20 47 0.4
20 53 0.4
20 72 0.4
20 92 0.4
20 105 0.4
20 167 0.4
20 170 0.4
21 11 0.01
21 16 -0.02
21 18 -0.02
21 24 -0.01
21 44 -0.02
21 65 0.01
21 69 -0.01
21 71 -0.01
21 77 -0.01
21 94 -0.01
21 104 0.01
21 112 -0.01
21 141 0.01
21 161 0.02
21 167 -0.01
21 192 0.01
21 208 0.02
21 219 -0.02
21 242 -0.01
21 247 -0.02
21 250 -0.01
21 256 0.01
21 263 -0.02
21 310 0.01
21 341 0.01
22 11 0.01
22 18 -0.01
22 44 -0.01
22 49 -0.01
22 69 -0.01
22 71 0.01
22 77 -0.01
22 94 -0.01
22 112 -0.01
22 141 -0.01
22 158 -0.01
22 161 0.01
22 167 -0.01
22 192 0.01
22 208 0.01
22 219 -0.01
22 224 0.01
22 242 -0.01
22 247 -0.01
22 250 0.01
22 256 0.01
22 263 -0.01
23 7 0.01
23 11 0.01
23 16 -0.02
23 18 -0.03
23 19 0.01
23 24 -0.01
23 30 -0.01
23 41 0.01
23 44 -0.02
23 49 0.01
23 65 0.01
23 71 -0.01
23 77 -0.01
23 94 -0.01
23 104 0.02
23 105 0.01
23 106 -0.01
23 112 -0.01
23 117 -0.01
23 141 0.02
23 144 0.01
23 161 0.02
23 167 -0.01
23 169 -0.01
23 188 0.01
23 192 0.01
23 208 0.02
23 219 -0.03
23 226 0.01
23 247 -0.02
23 250 -0.02
23 256 0.01
23 257 0.01
23 263 -0.02
23 310 0.01
23 341 0.01

In [209]:
for j in range(0,24):
    for i in range (0,348):
        if d.iloc[i,j]==True:
            #將離峰值改為空值
            Input2.iloc[i,j]=0
Input2

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
0,0.0,0.0,0.00,0.00,0.00,0.016,0.010,0.002,0.004,0.002,...,-0.02,-0.02,-0.03,-0.01,-0.03,0.1,0.500,0.0,0.0,0.0
1,0.0,0.0,0.00,0.00,0.00,0.002,0.013,0.002,0.002,0.002,...,-0.02,-0.02,-0.03,-0.02,-0.02,0.2,0.600,0.0,0.0,0.0
2,0.0,0.0,0.00,0.03,0.05,0.002,0.014,0.002,0.002,0.002,...,0.04,-0.04,-0.04,-0.05,-0.04,0.1,0.576,0.0,0.0,0.0
3,0.0,0.0,0.00,0.00,0.02,0.003,0.010,0.002,0.004,0.002,...,0.05,-0.02,-0.03,-0.01,-0.02,1.0,0.600,0.0,0.0,0.0
4,0.0,0.0,0.00,0.02,0.04,0.006,0.020,0.002,0.004,0.002,...,0.02,-0.05,-0.03,-0.03,-0.05,0.0,0.523,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,0.0,0.0,0.05,0.02,0.00,0.004,0.020,0.002,0.003,0.002,...,-0.02,-0.02,-0.03,-0.02,-0.02,0.2,0.500,0.0,0.0,0.0
344,0.0,0.0,0.00,0.00,0.00,0.006,0.020,0.002,0.004,0.002,...,0.05,-0.02,-0.02,-0.02,-0.02,0.5,0.547,0.0,0.0,0.0
345,0.0,0.0,0.00,0.02,0.04,0.002,0.004,0.002,0.004,0.002,...,-0.02,-0.01,-0.03,-0.02,-0.02,0.1,0.574,0.0,0.0,0.0
346,0.0,0.0,0.00,0.00,0.00,0.002,0.005,0.002,0.005,0.002,...,-0.02,-0.02,-0.02,-0.03,-0.02,0.1,0.500,0.0,0.0,0.0
347,0.0,0.0,0.04,0.02,0.00,0.002,0.005,0.002,0.005,0.002,...,-0.02,-0.02,-0.02,-0.04,-0.02,1.1,0.547,0.0,0.0,0.0

In [210]:
Input2.shape

(348, 24)

In [211]:
a.iloc[0:8,:]

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
count,348,348,348,348,348,348,348,348,348,348,...,346,346,346,346,346,346,346,348,348,348
mean,0.0228736,0.0181034,0.0125575,0.0172701,0.0211782,0.00599138,0.00966667,0.00200575,0.00338218,0.002,...,0.00760694,-0.0272832,-0.0279769,-0.027659,-0.0272254,0.521387,0.549717,-0.000258621,-0.000172414,-8.62069e-05
std,0.0467788,0.0386944,0.0204998,0.0476269,0.0329622,0.00438328,0.00522666,0.000107211,0.00109251,1.30292e-18,...,0.0303788,0.0124698,0.0117441,0.012944,0.012457,0.796117,0.0498,0.00374886,0.00251202,0.00477065
min,0,0,0,0,0,0.001,0.002,0.002,0.002,0.002,...,-0.05,-0.05,-0.05,-0.05,-0.05,0,0.4,-0.02,-0.01,-0.03
25%,0,0,0,0,0,0.002,0.005,0.002,0.002,0.002,...,-0.02,-0.04,-0.04,-0.04,-0.04,0.1,0.521,0,0,0
50%,0,0,0,0,0,0.004,0.01,0.002,0.003,0.002,...,0.02,-0.02,-0.03,-0.03,-0.03,0.2,0.562,0,0,0
75%,0,0,0.03,0.02,0.04,0.008,0.014,0.002,0.004,0.002,...,0.03,-0.02,-0.02,-0.02,-0.02,1,0.6,0,0,0
max,0.28,0.26,0.13,0.82,0.16,0.02,0.028,0.004,0.005,0.002,...,0.05,-0.01,-0.01,-0.01,-0.01,5.3,0.6,0.02,0.01,0.02

In [212]:
#去除離峰值
pd.DataFrame(Input2).describe()

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
count,348.0,348.0,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,3.480000e+02,...,346.000000,346.000000,346.000000,346.000000,346.000000,346.00000,346.000000,348.0,348.0,348.0
mean,0.0,0.0,0.010862,0.012040,0.017529,0.005618,0.009586,0.001994,0.003382,2.000000e-03,...,0.007607,-0.027283,-0.027977,-0.027659,-0.027225,0.38237,0.540468,0.0,0.0,0.0
std,0.0,0.0,0.016903,0.014628,0.027524,0.004073,0.005159,0.000107,0.001093,1.302916e-18,...,0.030379,0.012470,0.011744,0.012944,0.012457,0.50803,0.094243,0.0,0.0,0.0
min,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002000,2.000000e-03,...,-0.050000,-0.050000,-0.050000,-0.050000,-0.050000,0.00000,0.000000,0.0,0.0,0.0
25%,0.0,0.0,0.000000,0.000000,0.000000,0.002000,0.005000,0.002000,0.002000,2.000000e-03,...,-0.020000,-0.040000,-0.040000,-0.040000,-0.040000,0.10000,0.521000,0.0,0.0,0.0
50%,0.0,0.0,0.000000,0.000000,0.000000,0.004000,0.009500,0.002000,0.003000,2.000000e-03,...,0.020000,-0.020000,-0.030000,-0.030000,-0.030000,0.10000,0.562000,0.0,0.0,0.0
75%,0.0,0.0,0.020000,0.020000,0.030000,0.008000,0.013250,0.002000,0.004000,2.000000e-03,...,0.030000,-0.020000,-0.020000,-0.020000,-0.020000,0.82500,0.600000,0.0,0.0,0.0
max,0.0,0.0,0.070000,0.050000,0.100000,0.016000,0.024000,0.002000,0.005000,2.000000e-03,...,0.050000,-0.010000,-0.010000,-0.010000,-0.010000,2.20000,0.600000,0.0,0.0,0.0

In [213]:
#未去除離峰值
pd.DataFrame(Input3).describe()

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
count,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,3.480000e+02,...,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,348.000000,348.000000,348.000000
mean,0.022874,0.018103,0.012557,0.017270,0.021178,0.005991,0.009667,0.002006,0.003382,2.000000e-03,...,0.007607,-0.027283,-0.027977,-0.027659,-0.027225,0.521387,0.549717,-0.000259,-0.000172,-0.000086
std,0.046779,0.038694,0.020500,0.047627,0.032962,0.004383,0.005227,0.000107,0.001093,1.302916e-18,...,0.030379,0.012470,0.011744,0.012944,0.012457,0.796117,0.049800,0.003749,0.002512,0.004771
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.001000,0.002000,0.002000,0.002000,2.000000e-03,...,-0.050000,-0.050000,-0.050000,-0.050000,-0.050000,0.000000,0.400000,-0.020000,-0.010000,-0.030000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.002000,0.005000,0.002000,0.002000,2.000000e-03,...,-0.020000,-0.040000,-0.040000,-0.040000,-0.040000,0.100000,0.521000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.004000,0.010000,0.002000,0.003000,2.000000e-03,...,0.020000,-0.020000,-0.030000,-0.030000,-0.030000,0.200000,0.562000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.030000,0.020000,0.040000,0.008000,0.014000,0.002000,0.004000,2.000000e-03,...,0.030000,-0.020000,-0.020000,-0.020000,-0.020000,1.000000,0.600000,0.000000,0.000000,0.000000
max,0.280000,0.260000,0.130000,0.820000,0.160000,0.020000,0.028000,0.004000,0.005000,2.000000e-03,...,0.050000,-0.010000,-0.010000,-0.010000,-0.010000,5.300000,0.600000,0.020000,0.010000,0.020000