In [115]:
import pandas as pd 
import matplotlib.pyplot as plt 
# å°Žå…¥æ•¸æ“š 
data = pd.read_csv(r'C:/Users/Cindy/Desktop/0714train.csv')
Input_A1_001_024=data[['Input_A1_001','Input_A1_002','Input_A1_003','Input_A1_004','Input_A1_005','Input_A1_006','Input_A1_007','Input_A1_008','Input_A1_009','Input_A1_010','Input_A1_011','Input_A1_012','Input_A1_013','Input_A1_014','Input_A1_015','Input_A1_016','Input_A1_017','Input_A1_018','Input_A1_019','Input_A1_020','Input_A1_021','Input_A1_022','Input_A1_023','Input_A1_024']]
Input_A1=data[['Input_A1_001','Input_A1_002','Input_A1_003','Input_A1_004','Input_A1_005','Input_A1_006','Input_A1_007','Input_A1_008','Input_A1_009','Input_A1_010','Input_A1_011','Input_A1_012','Input_A1_013','Input_A1_014','Input_A1_015','Input_A1_016','Input_A1_017','Input_A1_018','Input_A1_019','Input_A1_020','Input_A1_021','Input_A1_022','Input_A1_023','Input_A1_024']]
Input_A1_001_024

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
0,0.00,0.00,0.00,0.00,0.00,0.016,0.010,0.002,0.004,0.002,...,-0.02,-0.02,-0.03,-0.01,-0.03,0.1,0.500,0.0,0.0,0.0
1,0.00,0.00,0.00,0.00,0.00,0.002,0.013,0.002,0.002,0.002,...,-0.02,-0.02,-0.03,-0.02,-0.02,0.2,0.600,0.0,0.0,0.0
2,0.00,0.00,0.00,0.03,0.05,0.002,0.014,0.002,0.002,0.002,...,0.04,-0.04,-0.04,-0.05,-0.04,0.1,0.576,0.0,0.0,0.0
3,0.00,0.00,0.00,0.00,0.02,0.003,0.010,0.002,0.004,0.002,...,0.05,-0.02,-0.03,-0.01,-0.02,1.0,0.600,0.0,0.0,0.0
4,0.00,0.00,0.00,0.02,0.04,0.006,0.020,0.002,0.004,0.002,...,0.02,-0.05,-0.03,-0.03,-0.05,0.0,0.523,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,0.12,0.09,0.05,0.02,0.00,0.004,0.020,0.002,0.003,0.002,...,-0.02,-0.02,-0.03,-0.02,-0.02,0.2,0.500,0.0,0.0,0.0
344,0.00,0.00,0.00,0.00,0.00,0.006,0.020,0.002,0.004,0.002,...,0.05,-0.02,-0.02,-0.02,-0.02,0.5,0.547,0.0,0.0,0.0
345,0.00,0.00,0.00,0.02,0.04,0.002,0.004,0.002,0.004,0.002,...,-0.02,-0.01,-0.03,-0.02,-0.02,0.1,0.574,0.0,0.0,0.0
346,0.00,0.00,0.00,0.00,0.00,0.002,0.005,0.002,0.005,0.002,...,-0.02,-0.02,-0.02,-0.03,-0.02,0.1,0.500,0.0,0.0,0.0
347,0.10,0.08,0.04,0.02,0.00,0.002,0.005,0.002,0.005,0.002,...,-0.02,-0.02,-0.02,-0.04,-0.02,1.1,0.547,0.0,0.0,0.0

In [116]:
pd.DataFrame(Input_A1_001_024).describe()

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
count,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,3.480000e+02,...,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,348.000000,348.000000,348.000000
mean,0.022874,0.018103,0.012557,0.017270,0.021178,0.005991,0.009667,0.002006,0.003382,2.000000e-03,...,0.007607,-0.027283,-0.027977,-0.027659,-0.027225,0.521387,0.549717,-0.000259,-0.000172,-0.000086
std,0.046779,0.038694,0.020500,0.047627,0.032962,0.004383,0.005227,0.000107,0.001093,1.302916e-18,...,0.030379,0.012470,0.011744,0.012944,0.012457,0.796117,0.049800,0.003749,0.002512,0.004771
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.001000,0.002000,0.002000,0.002000,2.000000e-03,...,-0.050000,-0.050000,-0.050000,-0.050000,-0.050000,0.000000,0.400000,-0.020000,-0.010000,-0.030000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.002000,0.005000,0.002000,0.002000,2.000000e-03,...,-0.020000,-0.040000,-0.040000,-0.040000,-0.040000,0.100000,0.521000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.004000,0.010000,0.002000,0.003000,2.000000e-03,...,0.020000,-0.020000,-0.030000,-0.030000,-0.030000,0.200000,0.562000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.030000,0.020000,0.040000,0.008000,0.014000,0.002000,0.004000,2.000000e-03,...,0.030000,-0.020000,-0.020000,-0.020000,-0.020000,1.000000,0.600000,0.000000,0.000000,0.000000
max,0.280000,0.260000,0.130000,0.820000,0.160000,0.020000,0.028000,0.004000,0.005000,2.000000e-03,...,0.050000,-0.010000,-0.010000,-0.010000,-0.010000,5.300000,0.600000,0.020000,0.010000,0.020000

In [117]:
a=pd.DataFrame(Input_A1_001_024).describe()
a.loc['IQR'] ='' 
a.loc['fence_max'] ='' 
a.loc['fence_min'] ='' 
for i in range(24):
    a.iloc[8,i]=a.iloc[6,i]-a.iloc[4,i]
    a.iloc[9,i]=a.iloc[6,i] + 1.5 * a.iloc[8,i]
    a.iloc[10,i]=a.iloc[4,i] - 1.5 * a.iloc[8,i]
a

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
count,348,348,348,348,348,348,348,348,348,348,...,346,346,346,346,346,346,346,348,348,348
mean,0.0228736,0.0181034,0.0125575,0.0172701,0.0211782,0.00599138,0.00966667,0.00200575,0.00338218,0.002,...,0.00760694,-0.0272832,-0.0279769,-0.027659,-0.0272254,0.521387,0.549717,-0.000258621,-0.000172414,-8.62069e-05
std,0.0467788,0.0386944,0.0204998,0.0476269,0.0329622,0.00438328,0.00522666,0.000107211,0.00109251,1.30292e-18,...,0.0303788,0.0124698,0.0117441,0.012944,0.012457,0.796117,0.0498,0.00374886,0.00251202,0.00477065
min,0,0,0,0,0,0.001,0.002,0.002,0.002,0.002,...,-0.05,-0.05,-0.05,-0.05,-0.05,0,0.4,-0.02,-0.01,-0.03
25%,0,0,0,0,0,0.002,0.005,0.002,0.002,0.002,...,-0.02,-0.04,-0.04,-0.04,-0.04,0.1,0.521,0,0,0
50%,0,0,0,0,0,0.004,0.01,0.002,0.003,0.002,...,0.02,-0.02,-0.03,-0.03,-0.03,0.2,0.562,0,0,0
75%,0,0,0.03,0.02,0.04,0.008,0.014,0.002,0.004,0.002,...,0.03,-0.02,-0.02,-0.02,-0.02,1,0.6,0,0,0
max,0.28,0.26,0.13,0.82,0.16,0.02,0.028,0.004,0.005,0.002,...,0.05,-0.01,-0.01,-0.01,-0.01,5.3,0.6,0.02,0.01,0.02
IQR,0,0,0.03,0.02,0.04,0.006,0.009,0,0.002,0,...,0.05,0.02,0.02,0.02,0.02,0.9,0.079,0,0,0
fence_max,0,0,0.075,0.05,0.1,0.017,0.0275,0.002,0.007,0.002,...,0.105,0.01,0.01,0.01,0.01,2.35,0.7185,0,0,0
fence_min,0,0,-0.045,-0.03,-0.06,-0.007,-0.0085,0.002,-0.001,0.002,...,-0.095,-0.07,-0.07,-0.07,-0.07,-1.25,0.4025,0,0,0

In [118]:
d=Input_A1_001_024
for i in range(0,24):
    fmin=a.iloc[10,i]
    fmax=a.iloc[9,i]
    tf=((d.iloc[:,i] < fmin) | (d.iloc[:,i] > (fmax)))
    d.iloc[:,i]=tf
d

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
344,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
345,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
346,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
347,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [119]:
Input_A1

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
0,0.00,0.00,0.00,0.00,0.00,0.016,0.010,0.002,0.004,0.002,...,-0.02,-0.02,-0.03,-0.01,-0.03,0.1,0.500,0.0,0.0,0.0
1,0.00,0.00,0.00,0.00,0.00,0.002,0.013,0.002,0.002,0.002,...,-0.02,-0.02,-0.03,-0.02,-0.02,0.2,0.600,0.0,0.0,0.0
2,0.00,0.00,0.00,0.03,0.05,0.002,0.014,0.002,0.002,0.002,...,0.04,-0.04,-0.04,-0.05,-0.04,0.1,0.576,0.0,0.0,0.0
3,0.00,0.00,0.00,0.00,0.02,0.003,0.010,0.002,0.004,0.002,...,0.05,-0.02,-0.03,-0.01,-0.02,1.0,0.600,0.0,0.0,0.0
4,0.00,0.00,0.00,0.02,0.04,0.006,0.020,0.002,0.004,0.002,...,0.02,-0.05,-0.03,-0.03,-0.05,0.0,0.523,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,0.12,0.09,0.05,0.02,0.00,0.004,0.020,0.002,0.003,0.002,...,-0.02,-0.02,-0.03,-0.02,-0.02,0.2,0.500,0.0,0.0,0.0
344,0.00,0.00,0.00,0.00,0.00,0.006,0.020,0.002,0.004,0.002,...,0.05,-0.02,-0.02,-0.02,-0.02,0.5,0.547,0.0,0.0,0.0
345,0.00,0.00,0.00,0.02,0.04,0.002,0.004,0.002,0.004,0.002,...,-0.02,-0.01,-0.03,-0.02,-0.02,0.1,0.574,0.0,0.0,0.0
346,0.00,0.00,0.00,0.00,0.00,0.002,0.005,0.002,0.005,0.002,...,-0.02,-0.02,-0.02,-0.03,-0.02,0.1,0.500,0.0,0.0,0.0
347,0.10,0.08,0.04,0.02,0.00,0.002,0.005,0.002,0.005,0.002,...,-0.02,-0.02,-0.02,-0.04,-0.02,1.1,0.547,0.0,0.0,0.0

In [120]:
for j in range(0,24):
    for i in range (0,348):
        if d.iloc[i,j]==True:
            print(j,i)

0 8
0 9
0 12
0 13
0 22
0 25
0 33
0 34
0 47
0 48
0 49
0 54
0 59
0 62
0 72
0 73
0 77
0 79
0 81
0 84
0 88
0 91
0 93
0 97
0 99
0 104
0 106
0 109
0 111
0 125
0 128
0 129
0 135
0 147
0 148
0 152
0 154
0 156
0 160
0 163
0 164
0 171
0 173
0 181
0 184
0 185
0 190
0 192
0 196
0 200
0 206
0 216
0 217
0 222
0 227
0 231
0 236
0 237
0 239
0 240
0 241
0 244
0 250
0 259
0 260
0 261
0 268
0 282
0 294
0 297
0 300
0 306
0 318
0 321
0 329
0 332
0 343
0 347
1 8
1 9
1 12
1 13
1 22
1 25
1 33
1 34
1 47
1 48
1 49
1 54
1 59
1 62
1 72
1 73
1 77
1 79
1 81
1 84
1 88
1 91
1 93
1 97
1 99
1 104
1 106
1 109
1 111
1 125
1 128
1 129
1 135
1 147
1 148
1 152
1 154
1 156
1 160
1 163
1 164
1 171
1 173
1 181
1 184
1 185
1 190
1 192
1 195
1 196
1 200
1 206
1 216
1 217
1 222
1 227
1 231
1 236
1 237
1 239
1 240
1 241
1 244
1 250
1 259
1 260
1 261
1 268
1 282
1 294
1 297
1 300
1 306
1 318
1 321
1 329
1 332
1 343
1 347
2 91
2 111
2 125
2 156
2 217
2 236
3 43
3 66
3 94
3 141
3 156
3 159
3 195
3 200
3 204
3 242
3 257
3 280
3 281
3 286
4 43
4 66
4 94
4 195
4 204
4 242
4 257
4 280
4 281
4 286
5 90
5 95
5 100
5 132
5 149
5 158
5 159
6 8
7 221
10 266
10 268
10 269
10 270
10 276
10 277
10 282
10 284
10 288
10 291
10 292
10 298
10 303
10 310
10 317
10 321
10 323
10 325
10 329
10 330
10 331
10 332
10 335
10 336
10 338
10 344
10 345
10 346
10 347
19 25
19 48
19 49
19 69
19 78
19 93
19 113
19 117
19 135
19 141
19 158
19 161
19 211
19 239
20 19
20 47
20 53
20 72
20 92
20 105
20 167
20 170
21 11
21 16
21 18
21 24
21 44
21 65
21 69
21 71
21 77
21 94
21 104
21 112
21 141
21 161
21 167
21 192
21 208
21 219
21 242
21 247
21 250
21 256
21 263
21 310
21 341
22 11
22 18
22 44
22 49
22 69
22 71
22 77
22 94
22 112
22 141
22 158
22 161
22 167
22 192
22 208
22 219
22 224
22 242
22 247
22 250
22 256
22 263
23 7
23 11
23 16
23 18
23 19
23 24
23 30
23 41
23 44
23 49
23 65
23 71
23 77
23 94
23 104
23 105
23 106
23 112
23 117
23 141
23 144
23 161
23 167
23 169
23 188
23 192
23 208
23 219
23 226
23 247
23 250
23 256
23 257
23 263
23 310
23 341

In [122]:
for j in range(0,24):
    for i in range (0,348):
        if d.iloc[i,j]==True:
            #å°‡é›¢å³°å€¼æ”¹ç‚ºnull
            Input_A1.iloc[i,j]='NULL'
Input_A1

,Input_A1_001,Input_A1_002,Input_A1_003,Input_A1_004,Input_A1_005,Input_A1_006,Input_A1_007,Input_A1_008,Input_A1_009,Input_A1_010,...,Input_A1_015,Input_A1_016,Input_A1_017,Input_A1_018,Input_A1_019,Input_A1_020,Input_A1_021,Input_A1_022,Input_A1_023,Input_A1_024
0,0,0,0,0,0,0.016,0.01,0.002,0.004,0.002,...,-0.02,-0.02,-0.03,-0.01,-0.03,0.1,0.5,0,0,0
1,0,0,0,0,0,0.002,0.013,0.002,0.002,0.002,...,-0.02,-0.02,-0.03,-0.02,-0.02,0.2,0.6,0,0,0
2,0,0,0,0.03,0.05,0.002,0.014,0.002,0.002,0.002,...,0.04,-0.04,-0.04,-0.05,-0.04,0.1,0.576,0,0,0
3,0,0,0,0,0.02,0.003,0.01,0.002,0.004,0.002,...,0.05,-0.02,-0.03,-0.01,-0.02,1,0.6,0,0,0
4,0,0,0,0.02,0.04,0.006,0.02,0.002,0.004,0.002,...,0.02,-0.05,-0.03,-0.03,-0.05,0,0.523,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,NULL,NULL,0.05,0.02,0,0.004,0.02,0.002,0.003,0.002,...,-0.02,-0.02,-0.03,-0.02,-0.02,0.2,0.5,0,0,0
344,0,0,0,0,0,0.006,0.02,0.002,0.004,0.002,...,0.05,-0.02,-0.02,-0.02,-0.02,0.5,0.547,0,0,0
345,0,0,0,0.02,0.04,0.002,0.004,0.002,0.004,0.002,...,-0.02,-0.01,-0.03,-0.02,-0.02,0.1,0.574,0,0,0
346,0,0,0,0,0,0.002,0.005,0.002,0.005,0.002,...,-0.02,-0.02,-0.02,-0.03,-0.02,0.1,0.5,0,0,0
347,NULL,NULL,0.04,0.02,0,0.002,0.005,0.002,0.005,0.002,...,-0.02,-0.02,-0.02,-0.04,-0.02,1.1,0.547,0,0,0

In [113]:
for j in range(0,24):
    for i in range (0,348):
        if d.iloc[i,j]==True:
            Input_A1=Input_A1.pop(Input_A1.iloc[i,j])
Input_A1

KeyError: 'NULL'

In [ ]:
df=pd.DataFrame(Input_A1)
indexNames = df.iloc[i,j].index
df.drop(indexNames , inplace=True)